DROP INDEX IF EXISTS "Club_slug_idx";
DROP INDEX IF EXISTS "Club_slug_key";

ALTER TABLE "Club"
DROP COLUMN IF EXISTS "slug",
DROP COLUMN IF EXISTS "address",
DROP COLUMN IF EXISTS "phone",
DROP COLUMN IF EXISTS "email",
DROP COLUMN IF EXISTS "imageUrl";

