export enum CustomerCommerceStatus {
  AVAILABLE = 'AVAILABLE',
  PAYMENTS_UNAVAILABLE = 'PAYMENTS_UNAVAILABLE',
}

export enum CustomerClubEmptyReason {
  PAYMENTS_UNAVAILABLE = 'PAYMENTS_UNAVAILABLE',
  NO_EVENTS_OR_OFFERS = 'NO_EVENTS_OR_OFFERS',
}

export enum CustomerHomeEmptyReason {
  NO_ACTIVE_CLUBS_IN_SCOPE = 'NO_ACTIVE_CLUBS_IN_SCOPE',
  PAYMENTS_UNAVAILABLE = 'PAYMENTS_UNAVAILABLE',
  NO_VISIBLE_EVENTS = 'NO_VISIBLE_EVENTS',
  NO_ACTIVE_PROMOTIONS = 'NO_ACTIVE_PROMOTIONS',
}
